# Generated by Django 5.1.1 on 2024-10-07 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='miniature',
            field=models.ImageField(null=True, upload_to='posts/img/'),
        ),
    ]
